### ISSUE TITLE
Some metrics are not displayed in monitoring tab

### ISSUE THREAD

**Issue by gikang82** [spaceone-dev/plugin-aws-cloudwatch-mon-datasource#46]

**Comment by gikang82** [comment]
- AWS cloudfront distribution metrics are not shown in spaceone console
- Some metrics from AWS resources are not displayed correctly
- Investigation the root cause is needed.

**Comment by jihyungSong** [comment]
To get the Cloudfront monitoring value, both `DistributionId` and `Region`(value is Global) are required as Dimension values. The scope to manage the Dimension value of Cloudwatch each Cloud service is the Collector plugin, and the related Commit is as follows.

https://github.com/spaceone-dev/plugin-aws-cloud-service-inven-collector/commit/a14925936611635b14943158f026c66a42d555a8

**Comment by jihyungSong** [comment]
As the monitoring metric will be refactoring as a whole, this issue ticket will be rearranged to the ticket "Refactoring Monitoring Metric" ([#207](https://github.com/orgs/spaceone-dev/projects/3))
